using System;
using Concentus.Structs;

namespace MicStreamReceiver.Services
{
    /// <summary>
    /// Opus Decoder service using Concentus library
    /// Decodes Opus-encoded audio to PCM
    /// </summary>
    public class OpusDecoderService : IDisposable
    {
        private readonly OpusDecoder _decoder;
        private readonly int _sampleRate;
        private readonly int _channels;
        private readonly int _frameSize;

        // Statistics
        private int _packetsDecoded;
        private int _plcFramesGenerated;

        public int PacketsDecoded => _packetsDecoded;
        public int PlcFramesGenerated => _plcFramesGenerated;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="sampleRate">Sample rate (default: 48000 Hz)</param>
        /// <param name="channels">Number of channels (default: 1 = Mono)</param>
        public OpusDecoderService(int sampleRate = 48000, int channels = 1)
        {
            _sampleRate = sampleRate;
            _channels = channels;
            _frameSize = (sampleRate / 1000) * 20; // 20ms frame = 960 samples at 48kHz

            // Initialize Opus decoder
            _decoder = new OpusDecoder(sampleRate, channels);
        }

        /// <summary>
        /// Decode Opus packet to PCM
        /// </summary>
        /// <param name="opusData">Opus-encoded audio data</param>
        /// <returns>PCM audio data (16-bit samples)</returns>
        public byte[] Decode(byte[] opusData)
        {
            if (opusData == null || opusData.Length == 0)
            {
                throw new ArgumentException("Opus data cannot be null or empty");
            }

            try
            {
                // Allocate buffer for decoded PCM (16-bit samples)
                short[] pcmSamples = new short[_frameSize * _channels];

                // Decode Opus to PCM
                int decodedSamples = _decoder.Decode(
                    opusData,
                    0,
                    opusData.Length,
                    pcmSamples,
                    0,
                    _frameSize
                );

                if (decodedSamples <= 0)
                {
                    throw new InvalidOperationException($"Opus decode failed: {decodedSamples} samples");
                }

                _packetsDecoded++;

                // Convert short[] to byte[]
                return ConvertSamplesToBytes(pcmSamples, decodedSamples);
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Failed to decode Opus packet: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Generate PCM data for missing packet using Packet Loss Concealment (PLC)
        /// </summary>
        /// <returns>PCM audio data generated by PLC</returns>
        public byte[] GeneratePlc()
        {
            try
            {
                // Allocate buffer for PLC PCM
                short[] pcmSamples = new short[_frameSize * _channels];

                // Opus decoder can generate replacement audio for missing packets
                // Pass null/empty data to trigger PLC
                int generatedSamples = _decoder.Decode(
                    null,
                    0,
                    0,
                    pcmSamples,
                    0,
                    _frameSize,
                    false // decodeFec = false for PLC
                );

                if (generatedSamples <= 0)
                {
                    // Fallback: return silence
                    return new byte[_frameSize * _channels * 2];
                }

                _plcFramesGenerated++;

                // Convert short[] to byte[]
                return ConvertSamplesToBytes(pcmSamples, generatedSamples);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[OPUS] PLC generation failed: {ex.Message}. Using silence.");
                // Fallback: return silence
                return new byte[_frameSize * _channels * 2];
            }
        }

        /// <summary>
        /// Convert short[] PCM samples to byte[] (little-endian)
        /// </summary>
        private byte[] ConvertSamplesToBytes(short[] samples, int sampleCount)
        {
            byte[] bytes = new byte[sampleCount * 2]; // 2 bytes per sample (16-bit)

            for (int i = 0; i < sampleCount; i++)
            {
                short sample = samples[i];
                bytes[i * 2] = (byte)(sample & 0xFF);           // Low byte
                bytes[i * 2 + 1] = (byte)((sample >> 8) & 0xFF); // High byte
            }

            return bytes;
        }

        /// <summary>
        /// Get decoder statistics
        /// </summary>
        public string GetStatistics()
        {
            return $"Decoded: {_packetsDecoded} packets, PLC: {_plcFramesGenerated} frames";
        }

        public void Dispose()
        {
            // Concentus OpusDecoder doesn't require explicit disposal
        }
    }
}
